### ISSUE TITLE
slack-sdk

### ISSUE THREAD

**Issue by fopina** [surface-security/django-notification-sender#13]
https://github.com/surface-security/django-notification-sender/blob/79aabf43cd1eead53ff4f1b5a812f6d97515524b/setup.cfg#L34

@gsilvapt why was the version increased? Is this newer version **required**?

Because it can (and it does, with django-slack-processor) introduce dependency conflicts. IMO we should only increase dependency versions if a feature in the package requires that. Otherwise, the widest range possible should be used.

**Comment by gsilvapt** [comment]
No reason, my mistake. Reverted in #14.
